on:
  push:
    branches:
    - "develop"

env:
  IMAGE_NAME: simple-api-java
  AZURE_WEBAPP_NAME: simple-api-java

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v4

      -   name: Setup Java SDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '21'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: index.docker.io/larifar/simple-api-java:latest
          file: ./Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      -
        name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fiap-on-api-dev'
          slots-name: 'production'
          publish-profile: ${{ secrets.AZURE_PROFILE}}
          images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/simple-api-java:latest'